// <auto-generated />
namespace Komsky.Data.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products));
        
        string IMigrationMetadata.Id
        {
            get { return "201512171151109_Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
